#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pedidos")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserteDetallePedido(eDetallePedido instance);
    partial void UpdateeDetallePedido(eDetallePedido instance);
    partial void DeleteeDetallePedido(eDetallePedido instance);
    partial void InserteProducto(eProducto instance);
    partial void UpdateeProducto(eProducto instance);
    partial void DeleteeProducto(eProducto instance);
    partial void InserteUsuario(eUsuario instance);
    partial void UpdateeUsuario(eUsuario instance);
    partial void DeleteeUsuario(eUsuario instance);
    partial void InsertePedido(ePedido instance);
    partial void UpdateePedido(ePedido instance);
    partial void DeleteePedido(ePedido instance);
    #endregion
		
		public DCDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.PedidosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<eDetallePedido> eDetallePedido
		{
			get
			{
				return this.GetTable<eDetallePedido>();
			}
		}
		
		public System.Data.Linq.Table<eProducto> eProducto
		{
			get
			{
				return this.GetTable<eProducto>();
			}
		}
		
		public System.Data.Linq.Table<eUsuario> eUsuario
		{
			get
			{
				return this.GetTable<eUsuario>();
			}
		}
		
		public System.Data.Linq.Table<ePedido> ePedido
		{
			get
			{
				return this.GetTable<ePedido>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetallePedido")]
	public partial class eDetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _fkProducto;
		
		private System.Nullable<int> _fkPedido;
		
		private System.Nullable<int> _cantidad;
		
		private EntityRef<eProducto> _eProducto;
		
		private EntityRef<ePedido> _ePedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfkProductoChanging(System.Nullable<int> value);
    partial void OnfkProductoChanged();
    partial void OnfkPedidoChanging(System.Nullable<int> value);
    partial void OnfkPedidoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public eDetallePedido()
		{
			this._eProducto = default(EntityRef<eProducto>);
			this._ePedido = default(EntityRef<ePedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkProducto", DbType="Int")]
		public System.Nullable<int> fkProducto
		{
			get
			{
				return this._fkProducto;
			}
			set
			{
				if ((this._fkProducto != value))
				{
					if (this._eProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkProductoChanging(value);
					this.SendPropertyChanging();
					this._fkProducto = value;
					this.SendPropertyChanged("fkProducto");
					this.OnfkProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkPedido", DbType="Int")]
		public System.Nullable<int> fkPedido
		{
			get
			{
				return this._fkPedido;
			}
			set
			{
				if ((this._fkPedido != value))
				{
					if (this._ePedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkPedidoChanging(value);
					this.SendPropertyChanging();
					this._fkPedido = value;
					this.SendPropertyChanged("fkPedido");
					this.OnfkPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eProducto_eDetallePedido", Storage="_eProducto", ThisKey="fkProducto", OtherKey="id", IsForeignKey=true)]
		public eProducto eProducto
		{
			get
			{
				return this._eProducto.Entity;
			}
			set
			{
				eProducto previousValue = this._eProducto.Entity;
				if (((previousValue != value) 
							|| (this._eProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eProducto.Entity = null;
						previousValue.eDetallePedido.Remove(this);
					}
					this._eProducto.Entity = value;
					if ((value != null))
					{
						value.eDetallePedido.Add(this);
						this._fkProducto = value.id;
					}
					else
					{
						this._fkProducto = default(Nullable<int>);
					}
					this.SendPropertyChanged("eProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_eDetallePedido", Storage="_ePedido", ThisKey="fkPedido", OtherKey="id", IsForeignKey=true)]
		public ePedido ePedido
		{
			get
			{
				return this._ePedido.Entity;
			}
			set
			{
				ePedido previousValue = this._ePedido.Entity;
				if (((previousValue != value) 
							|| (this._ePedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ePedido.Entity = null;
						previousValue.eDetallePedido.Remove(this);
					}
					this._ePedido.Entity = value;
					if ((value != null))
					{
						value.eDetallePedido.Add(this);
						this._fkPedido = value.id;
					}
					else
					{
						this._fkPedido = default(Nullable<int>);
					}
					this.SendPropertyChanged("ePedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class eProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private EntitySet<eDetallePedido> _eDetallePedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public eProducto()
		{
			this._eDetallePedido = new EntitySet<eDetallePedido>(new Action<eDetallePedido>(this.attach_eDetallePedido), new Action<eDetallePedido>(this.detach_eDetallePedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eProducto_eDetallePedido", Storage="_eDetallePedido", ThisKey="id", OtherKey="fkProducto")]
		public EntitySet<eDetallePedido> eDetallePedido
		{
			get
			{
				return this._eDetallePedido;
			}
			set
			{
				this._eDetallePedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eDetallePedido(eDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.eProducto = this;
		}
		
		private void detach_eDetallePedido(eDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.eProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class eUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _contraseña;
		
		private EntitySet<ePedido> _ePedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
		
		public eUsuario()
		{
			this._ePedido = new EntitySet<ePedido>(new Action<ePedido>(this.attach_ePedido), new Action<ePedido>(this.detach_ePedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(100)")]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eUsuario_Pedido", Storage="_ePedido", ThisKey="id", OtherKey="fkUsuario")]
		public EntitySet<ePedido> ePedido
		{
			get
			{
				return this._ePedido;
			}
			set
			{
				this._ePedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ePedido(ePedido entity)
		{
			this.SendPropertyChanging();
			entity.eUsuario = this;
		}
		
		private void detach_ePedido(ePedido entity)
		{
			this.SendPropertyChanging();
			entity.eUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class ePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _fkUsuario;
		
		private string _direccion;
		
		private System.Nullable<System.DateTime> _fechaCreacion;
		
		private System.Nullable<System.DateTime> _fechaDespacho;
		
		private System.Nullable<bool> _despachado;
		
		private EntitySet<eDetallePedido> _eDetallePedido;
		
		private EntityRef<eUsuario> _eUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfkUsuarioChanging(System.Nullable<int> value);
    partial void OnfkUsuarioChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnfechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaCreacionChanged();
    partial void OnfechaDespachoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaDespachoChanged();
    partial void OndespachadoChanging(System.Nullable<bool> value);
    partial void OndespachadoChanged();
    #endregion
		
		public ePedido()
		{
			this._eDetallePedido = new EntitySet<eDetallePedido>(new Action<eDetallePedido>(this.attach_eDetallePedido), new Action<eDetallePedido>(this.detach_eDetallePedido));
			this._eUsuario = default(EntityRef<eUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkUsuario", DbType="Int")]
		public System.Nullable<int> fkUsuario
		{
			get
			{
				return this._fkUsuario;
			}
			set
			{
				if ((this._fkUsuario != value))
				{
					if (this._eUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkUsuarioChanging(value);
					this.SendPropertyChanging();
					this._fkUsuario = value;
					this.SendPropertyChanged("fkUsuario");
					this.OnfkUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaDespacho", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaDespacho
		{
			get
			{
				return this._fechaDespacho;
			}
			set
			{
				if ((this._fechaDespacho != value))
				{
					this.OnfechaDespachoChanging(value);
					this.SendPropertyChanging();
					this._fechaDespacho = value;
					this.SendPropertyChanged("fechaDespacho");
					this.OnfechaDespachoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_despachado", DbType="Bit")]
		public System.Nullable<bool> despachado
		{
			get
			{
				return this._despachado;
			}
			set
			{
				if ((this._despachado != value))
				{
					this.OndespachadoChanging(value);
					this.SendPropertyChanging();
					this._despachado = value;
					this.SendPropertyChanged("despachado");
					this.OndespachadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_eDetallePedido", Storage="_eDetallePedido", ThisKey="id", OtherKey="fkPedido")]
		public EntitySet<eDetallePedido> eDetallePedido
		{
			get
			{
				return this._eDetallePedido;
			}
			set
			{
				this._eDetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eUsuario_Pedido", Storage="_eUsuario", ThisKey="fkUsuario", OtherKey="id", IsForeignKey=true)]
		public eUsuario eUsuario
		{
			get
			{
				return this._eUsuario.Entity;
			}
			set
			{
				eUsuario previousValue = this._eUsuario.Entity;
				if (((previousValue != value) 
							|| (this._eUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eUsuario.Entity = null;
						previousValue.ePedido.Remove(this);
					}
					this._eUsuario.Entity = value;
					if ((value != null))
					{
						value.ePedido.Add(this);
						this._fkUsuario = value.id;
					}
					else
					{
						this._fkUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("eUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eDetallePedido(eDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.ePedido = this;
		}
		
		private void detach_eDetallePedido(eDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.ePedido = null;
		}
	}
}
#pragma warning restore 1591
